name: auto-assemble

on:
  push:
    branches: ["main"]
    
jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
    - name: Run build with Gradle Wrapper
      run: ./gradlew assembleRelease
